version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_hoc
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack_hoc
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
      - "8002:8001"
    environment:
      - REDIS_ARGS=--requirepass rootredis 
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
    app-network:
      driver: bridge

